# Using Pandas

In [80]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [158]:
vehicles_df = pd.read_csv("data/vehicles.csv")
vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [139]:
## Your Code here df.Info()
#df.count())
#df.describe())
#df.mean())

vehicles_df.count()

Make                       35952
Model                      35952
Year                       35952
Engine Displacement        35952
Cylinders                  35952
Transmission               35952
Drivetrain                 35952
Vehicle Class              35952
Fuel Type                  35952
Fuel Barrels/Year          35952
City MPG                   35952
Highway MPG                35952
Combined MPG               35952
CO2 Emission Grams/Mile    35952
Fuel Cost/Year             35952
dtype: int64

In [140]:
vehicles_df.describe()

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
count,35952.00000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000,35952.000000
mean,2000.71640,3.338493,5.765076,17.609056,17.646139,23.880646,19.929322,475.316339,1892.598465
std,10.08529,1.359395,1.755268,4.467283,4.769349,5.890876,5.112409,119.060773,506.958627
min,1984.00000,0.600000,2.000000,0.060000,6.000000,9.000000,7.000000,37.000000,600.000000
25%,1991.00000,2.200000,4.000000,14.699423,15.000000,20.000000,16.000000,395.000000,1500.000000
50%,2001.00000,3.000000,6.000000,17.347895,17.000000,24.000000,19.000000,467.736842,1850.000000
75%,2010.00000,4.300000,6.000000,20.600625,20.000000,27.000000,23.000000,555.437500,2200.000000
max,2017.00000,8.400000,16.000000,47.087143,58.000000,61.000000,56.000000,1269.571429,5800.000000

In [141]:
type(vehicles_df)

pandas.core.frame.DataFrame

In [142]:
vehicles_df.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [143]:
list(vehicles_df.columns)

['Make',
 'Model',
 'Year',
 'Engine Displacement',
 'Cylinders',
 'Transmission',
 'Drivetrain',
 'Vehicle Class',
 'Fuel Type',
 'Fuel Barrels/Year',
 'City MPG',
 'Highway MPG',
 'Combined MPG',
 'CO2 Emission Grams/Mile',
 'Fuel Cost/Year']

In [144]:
#other version. We become an object - Index
column_names = (vehicles_df.columns)
print(column_names)
type(column_names)

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

pandas.core.indexes.base.Index

In [145]:
#other version. We become a list
column_names = (list(vehicles_df.columns))
print(column_names)
type(column_names)

['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders', 'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type', 'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG', 'CO2 Emission Grams/Mile', 'Fuel Cost/Year']

list

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

Note:
<br>Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Converting Gallons to Liters

1 Gallon = 3.78541 Liters

In [159]:
## Your Code here
#LOC
vehicles_df[vehicles_df["Make"].str.contains("Dutton")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,"E. P. Dutton, Inc.",Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,S and S Coach Company E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Superior Coaches Div E.p. Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

In [160]:
#students_df.iloc[:4, 4] = [40, 50, 60, 70]

vehicles_df.loc[vehicles_df["Make"].str.contains("Dutton"), 'Make'] = 'Dutton'

In [161]:
vehicles_df[vehicles_df["Make"].str.contains("Dutton")]

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11012,Dutton,Funeral Coach,1985,4.1,8.0,Automatic 4-spd,Front-Wheel Drive,Special Purpose Vehicles,Regular,19.388824,15,21,17,522.764706,1950
30164,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,9,11,10,888.700000,3350
31754,Dutton,Funeral Coach 2WD,1984,6.0,8.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,32.961000,10,11,10,888.700000,3350

In [162]:
#Convert CO2 Emissions from Grams/Mile to Grams/Km
#1 Mile = 1.60934 Km
#students_df["py-score"]=students_df["py-score"]  * 1.5

vehicles_df["CO2 Emission Grams/Mile"] = vehicles_df['CO2 Emission Grams/Mile'] / 1.6 

vehicles_df["CO2 Emission Grams/Mile"]

0        326.727941
1        427.259615
2        347.148438
3        427.259615
4        347.148438
            ...
35947    152.500000
35948    151.875000
35949    152.500000
35950    153.750000
35951    159.375000
Name: CO2 Emission Grams/Mile, Length: 35952, dtype: float64

In [163]:
vehicles_df.rename(columns={"CO2 Emission Grams/Mile": "CO2 Emission Grams/km"})

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,326.727941,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,427.259615,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,347.148438,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,427.259615,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,347.148438,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,152.500000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,151.875000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,152.500000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,153.750000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,159.375000,1150

In [180]:
#Create a binary column that solely indicates if the transmission of a car is automatic or manual. 
#Use pandas.Series.str.startswith and convert MPG columns to km_per_liter 



def auto_manual_function(Transmission):
    if Transmission.startswith('A'):
        return "Auto"
    else:
        return "Manual"
    

#vehicles_df["AUTO_or_MANUAL"]= vehicles_df["AUTO_or_MANUAL"].apply(auto_manual_function)


vehicles_df.insert(loc = 15, column ='AUTO_or_MANUAL', value = vehicles_df["Transmission"].apply(auto_manual_function))

vehicles_df

ValueError: cannot insert AUTO_or_MANUAL, already exists

In [181]:
#Use pandas.Series.str.startswith and convert MPG columns to km_per_liter 
#Converting Gallons to Liters
#1 Gallon = 3.78541 Liters

def update_km_per_liter(x):
    return x / 1.6 * 3.7 
    

vehicles_df[["City MPG", 'Highway MPG', 'Combined MPG']]= vehicles_df[['City MPG', 'Highway MPG', 'Combined MPG']].apply(update_km_per_liter)

vehicles_df.rename(columns={"City MPG": "City KMPL"})


vehicles_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City KMPL,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,AUTO_or_MANUAL
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,3.969669,9.597778,9.597778,326.727941,1950,Auto
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.866983,7.339478,7.339478,427.259615,2550,Auto
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,3.528595,9.597778,9.033203,347.148438,2100,Auto
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.866983,7.339478,7.339478,427.259615,2550,Auto
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,3.087521,11.856079,9.033203,347.148438,2550,Auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,152.500000,1100,Auto
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,151.875000,1100,Auto
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,152.500000,1100,Auto
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,22.018433,20.324707,153.750000,1100,Auto
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,7.057190,22.018433,19.760132,159.375000,1150,Manual

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,AUTO_or_MANUAL
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,3.969669,9.597778,9.597778,326.727941,1950,Auto
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.866983,7.339478,7.339478,427.259615,2550,Auto
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,3.528595,9.597778,9.033203,347.148438,2100,Auto
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,2.866983,7.339478,7.339478,427.259615,2550,Auto
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,3.087521,11.856079,9.033203,347.148438,2550,Auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,152.500000,1100,Auto
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,151.875000,1100,Auto
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,21.453857,20.324707,152.500000,1100,Auto
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,7.498264,22.018433,20.324707,153.750000,1100,Auto
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,7.057190,22.018433,19.760132,159.375000,1150,Manual

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [344]:
#How many car makers are there?

        #vehicles_df.loc[:, 'Make'].sort_values()
        #vehicles_df.sort_values(groupby = ["Make"])
        #car_makers = list(vehicles_df.groupby("Make").groups)
        #print(vehicles_df.groupby(["Make"])['Make'].count())
        #car_makers
        #len(car_makers)
        #car_maker_dict = vehicles_df.groupby(["Make"])
        #count = 0
        #for key, value in car_maker_dict.items():
               # print(car_maker_dict.keys, count + len(value))

        #most_car_maker = car_maker_dict.values()  
        #type(most_car_maker)
        #most_car_maker
        #car_maker_dict

        #https://sparkbyexamples.com/pandas/pandas-add-column-to-dataframe/

print(vehicles_df.groupby(["Make"]).ngroups)

# How many models
print(vehicles_df.groupby('Model').ngroups)

# Which car maker has the most cars in the dataset?
vehicles_df.groupby(["Make"])['Make'].count().sort_values(ascending=False)

125
3608

Make
Chevrolet                           3643
Ford                                2946
Dodge                               2360
GMC                                 2347
Toyota                              1836
BMW                                 1677
Mercedes-Benz                       1284
Nissan                              1253
Volkswagen                          1047
Mitsubishi                           950
Mazda                                915
Audi                                 890
Porsche                              862
Honda                                836
Jeep                                 829
Pontiac                              784
Subaru                               781
Volvo                                717
Hyundai                              662
Chrysler                             641
Buick                                537
Mercury                              532
Suzuki                               512
Cadillac                             508
Kia                                  493
Plymouth                             456
Saab                                 410
Isuzu                                409
Lexus                                397
Oldsmobile                           376
Infiniti                             345
Jaguar                               343
MINI                                 320
Acura                                302
Saturn                               278
Lincoln                              273
Ferrari                              208
Rolls-Royce                          160
Eagle                                156
Geo                                  144
Land Rover                           142
Aston Martin                         133
Bentley                              116
Maserati                             111
Lamborghini                          104
Scion                                 83
Peugeot                               74
Daewoo                                67
Ram                                   57
Lotus                                 53
Roush Performance                     53
Fiat                                  43
Alfa Romeo                            41
J.K. Motors                           36
Renault                               33
Wallace Environmental                 32
Maybach                               31
American Motors Corporation           22
smart                                 20
Hummer                                19
Daihatsu                              17
CX Automotive                         16
Merkur                                14
Federal Coach                         14
Import Trade Services                 13
McLaren Automotive                    13
Spyker                                13
Sterling                              12
Bugatti                                8
Yugo                                   8
Genesis                                7
Tecstar, LP                            6
Mcevoy Motors                          6
Bertone                                5
VPG                                    5
Saleen                                 5
Panther Car Company Limited            4
Saleen Performance                     4
AM General                             4
Grumman Olson                          4
Texas Coach Company                    4
Vector                                 4
Autokraft Limited                      4
TVR Engineering Ltd                    4
Bitter Gmbh and Co. Kg                 3
Evans Automobiles                      3
BMW Alpina                             3
Consulier Industries Inc               3
Dabryan Coach Builders Inc             3
Dacia                                  3
Dutton                                 3
Morgan                                 3
Ruf Automobile Gmbh                    2
Bill Dovell Motor Car Company          2
Mobility Ventures LLC                  2
Laforza Automobile Inc                 2
CCC Engineering                        2
PAS Inc - GMC                          2
PAS, Inc                               2
SRT                                    2
Pagani                                 2
Red Shift Ltd.                         2
Pininfarina                            2
Quantum Technologies                   2
Isis Imports Ltd                       1
Mahindra                               1
ASC Incorporated                       1
Aurora Cars Ltd                        1
Volga Associated Automobile            1
Vixen Motor Company                    1
JBA Motorcars, Inc.                    1
London Coach Co Inc                    1
London Taxi                            1
Import Foreign Auto Sales Inc          1
Environmental Rsch and Devp Corp       1
Grumman Allied Industries              1
Goldacre                               1
General Motors                         1
Shelby                                 1
Fisker                                 1
Panos                                  1
Panoz Auto-Development                 1
Excalibur Autos                        1
Qvale                                  1
Lambda Control Systems                 1
Name: Make, dtype: int64

In [376]:
#When were these cars made? 

print(vehicles_df.groupby('Year') ['Year'].count().sort_values())

Year
1984     645
1997     755
1996     767
1998     791
2000     827
1999     828
2017     857
2001     902
1995     928
2002     961
1994     967
2003    1034
1990    1068
1993    1077
2006    1099
1992    1107
2010    1108
2004    1113
1988    1119
1991    1122
2011    1124
2007    1126
1989    1127
2012    1139
2005    1156
2013    1168
2009    1183
2008    1184
1986    1188
1987    1198
2014    1211
2016    1228
2015    1264
1985    1581
Name: Year, dtype: int64

In [392]:
#How big is the engine of these cars?

print(vehicles_df.groupby('Engine Displacement') ['Engine Displacement'].max().sort_values(ascending=False))

Engine Displacement
8.4    8.4
8.3    8.3
8.0    8.0
7.4    7.4
7.0    7.0
6.8    6.8
6.7    6.7
6.6    6.6
6.5    6.5
6.4    6.4
6.3    6.3
6.2    6.2
6.1    6.1
6.0    6.0
5.9    5.9
5.8    5.8
5.7    5.7
5.6    5.6
5.5    5.5
5.4    5.4
5.3    5.3
5.2    5.2
5.0    5.0
4.9    4.9
4.8    4.8
4.7    4.7
4.6    4.6
4.5    4.5
4.4    4.4
4.3    4.3
4.2    4.2
4.1    4.1
4.0    4.0
3.9    3.9
3.8    3.8
3.7    3.7
3.6    3.6
3.5    3.5
3.4    3.4
3.3    3.3
3.2    3.2
3.1    3.1
3.0    3.0
2.9    2.9
2.8    2.8
2.7    2.7
2.6    2.6
2.5    2.5
2.4    2.4
2.3    2.3
2.2    2.2
2.1    2.1
2.0    2.0
1.9    1.9
1.8    1.8
1.7    1.7
1.6    1.6
1.5    1.5
1.4    1.4
1.3    1.3
1.2    1.2
1.1    1.1
1.0    1.0
0.9    0.9
0.6    0.6
Name: Engine Displacement, dtype: float64

In [428]:
#What's the frequency of different transmissions, drivetrains and fuel types?
vehicles_df.groupby('Transmission').count()
len(vehicles_df.groupby('Transmission').count())

vehicles_df.groupby('Drivetrain').count()
len(vehicles_df.groupby('Drivetrain').count())

,Make,Model,Year,Engine Displacement,Cylinders,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,AUTO_or_MANUAL,count
Transmission,,,,,,,,,,,,,,,,
Auto (AV),2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Auto (AV-S6),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Auto (AV-S8),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Auto(A1),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Auto(AM-S6),92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,0
Auto(AM-S7),256,256,256,256,256,256,256,256,256,256,256,256,256,256,256,0
Auto(AM-S8),6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,0
Auto(AM-S9),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Auto(AM5),12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0
Auto(AM6),110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,0
Auto(AM7),157,157,157,157,157,157,157,157,157,157,157,157,157,157,157,0
Auto(AM8),5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,0
Auto(AV-S6),145,145,145,145,145,145,145,145,145,145,145,145,145,145,145,0
Auto(AV-S7),63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,0
Auto(AV-S8),26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,0
Auto(L3),2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Auto(L4),2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Automatic (A1),3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0
Automatic (A6),4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
Automatic (AM5),2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0
Automatic (AM6),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Automatic (AV),4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,0
Automatic (AV-S6),9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,0
Automatic (S4),229,229,229,229,229,229,229,229,229,229,229,229,229,229,229,0
Automatic (S5),822,822,822,822,822,822,822,822,822,822,822,822,822,822,822,0
Automatic (S6),2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,2631,0
Automatic (S7),261,261,261,261,261,261,261,261,261,261,261,261,261,261,261,0
Automatic (S8),960,960,960,960,960,960,960,960,960,960,960,960,960,960,960,0
Automatic (S9),26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,0
Automatic (variable gear ratios),675,675,675,675,675,675,675,675,675,675,675,675,675,675,675,0
Automatic 3-spd,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,2597,0
Automatic 4-spd,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,10585,0
Automatic 5-spd,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,2171,0
Automatic 6-spd,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,1432,0
Automatic 6spd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Automatic 7-spd,662,662,662,662,662,662,662,662,662,662,662,662,662,662,662,0
Automatic 8-spd,243,243,243,243,243,243,243,243,243,243,243,243,243,243,243,0
Automatic 9-spd,90,90,90,90,90,90,90,90,90,90,90,90,90,90,90,0
Manual 3-spd,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,0
Manual 4-spd,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,1306,0
Manual 5 spd,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
Manual 5-spd,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,7787,0
Manual 6-spd,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,2423,0
Manual 7-spd,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,0
Manual(M7),3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0

45

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,AUTO_or_MANUAL,count
Drivetrain,,,,,,,,,,,,,,,,
2-Wheel Drive,423,423,423,423,423,423,423,423,423,423,423,423,423,423,423,0
"2-Wheel Drive, Front",1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0
4-Wheel Drive,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,1058,0
4-Wheel or All-Wheel Drive,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,6503,0
All-Wheel Drive,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,2039,0
Front-Wheel Drive,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,13044,0
Part-time 4-Wheel Drive,158,158,158,158,158,158,158,158,158,158,158,158,158,158,158,0
Rear-Wheel Drive,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,12726,0

8

In [426]:
vehicles_df.groupby('Fuel Type').count()
len(vehicles_df.groupby('Fuel Type').count())

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,AUTO_or_MANUAL,count
Fuel Type,,,,,,,,,,,,,,,,
CNG,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,0
Diesel,911,911,911,911,911,911,911,911,911,911,911,911,911,911,911,0
Gasoline or E85,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,1195,0
Gasoline or natural gas,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,0
Gasoline or propane,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,0
Midgrade,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,0
Premium,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,9921,0
Premium Gas or Electricity,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,0
Premium and Electricity,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,0
Premium or E85,121,121,121,121,121,121,121,121,121,121,121,121,121,121,121,0
Regular,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,23587,0
Regular Gas and Electricity,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,0
Regular Gas or Electricity,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,0

13

In [454]:
#What's the car that consumes the least/most fuel?
vehicles_df.groupby('Fuel Barrels/Year') ['Fuel Barrels/Year'].max().sort_values(ascending=False)
#47.087143 #0.060000

vehicles_df.groupby('Make') ['Fuel Barrels/Year'].max().sort_values(ascending=False)

most_fuel_consum = vehicles_df.groupby('Make') ['Fuel Barrels/Year'].max().sort_values(ascending=False)
#print(most_fuel_consum[key][0]

Fuel Barrels/Year
47.087143    47.087143
41.201250    41.201250
36.623333    36.623333
32.961000    32.961000
29.964545    29.964545
27.467500    27.467500
27.298929    27.298929
25.479000    25.479000
25.354615    25.354615
23.886563    23.886563
23.543571    23.543571
22.481471    22.481471
21.974000    21.974000
21.232500    21.232500
20.600625    20.600625
20.115000    20.115000
19.388824    19.388824
19.109250    19.109250
18.311667    18.311667
18.199286    18.199286
17.372045    17.372045
17.347895    17.347895
16.616739    16.616739
16.480500    16.480500
15.924375    15.924375
15.695714    15.695714
15.287400    15.287400
14.982273    14.982273
14.699423    14.699423
14.330870    14.330870
14.155000    14.155000
13.733750    13.733750
13.649464    13.649464
13.184400    13.184400
13.178793    13.178793
12.739500    12.739500
12.677308    12.677308
12.328548    12.328548
12.207778    12.207778
11.943281    11.943281
11.771786    11.771786
11.581364    11.581364
11.365862    11.365862
11.240735    11.240735
10.987000    10.987000
10.919571    10.919571
10.803703    10.803703
10.794366    10.794366
10.632581    10.632581
10.616250    10.616250
10.402951    10.402951
10.329324    10.329324
10.300313    10.300313
10.057500    10.057500
9.988182      9.988182
9.799615      9.799615
9.694412      9.694412
9.554625      9.554625
9.535201      9.535201
9.532027      9.532027
9.417429      9.417429
9.179989      9.179989
9.178874      9.178874
9.155833      9.155833
8.908378      8.908378
8.673947      8.673947
8.670674      8.670674
8.652550      8.652550
8.451538      8.451538
8.246835      8.246835
8.240250      8.240250
8.099619      8.099619
8.076981      8.076981
8.039268      8.039268
8.009330      8.009330
7.984573      7.984573
7.847857      7.847857
7.665349      7.665349
7.491136      7.491136
7.356924      7.356924
7.324667      7.324667
7.165435      7.165435
7.071000      7.071000
7.012979      7.012979
6.866875      6.866875
6.592200      6.592200
6.359255      6.359255
6.338654      6.338654
6.219057      6.219057
5.885893      5.885893
5.863280      5.863280
5.846634      5.846634
5.115503      5.115503
4.878704      4.878704
4.877585      4.877585
4.827657      4.827657
4.744612      4.744612
4.737144      4.737144
4.184202      4.184202
4.028975      4.028975
3.880578      3.880578
3.835583      3.835583
3.614242      3.614242
3.504650      3.504650
3.375621      3.375621
3.092539      3.092539
2.006844      2.006844
1.563190      1.563190
0.206667      0.206667
0.186000      0.186000
0.169091      0.169091
0.155000      0.155000
0.143077      0.143077
0.132857      0.132857
0.124000      0.124000
0.116250      0.116250
0.109412      0.109412
0.103333      0.103333
0.084545      0.084545
0.080870      0.080870
0.068889      0.068889
0.066429      0.066429
0.060000      0.060000
Name: Fuel Barrels/Year, dtype: float64

Make
Lamborghini                         47.087143
Ferrari                             41.201250
Vector                              41.201250
Aston Martin                        41.201250
Rolls-Royce                         41.201250
Maserati                            41.201250
Dodge                               36.623333
Chevrolet                           36.623333
Ford                                36.623333
Land Rover                          32.961000
Bugatti                             32.961000
Toyota                              32.961000
Dutton                              32.961000
Wallace Environmental               32.961000
Jeep                                29.964545
Laforza Automobile Inc              29.964545
Bentley                             29.964545
Roush Performance                   29.964545
Porsche                             29.964545
GMC                                 29.964545
J.K. Motors                         29.964545
Nissan                              29.964545
Mercedes-Benz                       29.964545
Jaguar                              27.467500
Lincoln                             27.467500
Lexus                               27.467500
Maybach                             27.467500
Plymouth                            27.467500
BMW                                 27.467500
Texas Coach Company                 27.467500
Cadillac                            27.467500
Pagani                              25.354615
Ruf Automobile Gmbh                 25.354615
Saab                                25.354615
Saleen                              25.354615
Saleen Performance                  25.354615
Tecstar, LP                         25.354615
Volkswagen                          25.354615
AM General                          25.354615
Alfa Romeo                          25.354615
Vixen Motor Company                 23.886563
Lotus                               23.543571
Infiniti                            23.543571
Mercury                             23.543571
Mitsubishi                          23.543571
PAS, Inc                            23.543571
Excalibur Autos                     23.543571
Federal Coach                       23.543571
Audi                                23.543571
Isuzu                               23.543571
Import Trade Services               23.543571
Hummer                              23.543571
Chrysler                            23.543571
Acura                               23.543571
Bitter Gmbh and Co. Kg              21.974000
Mazda                               21.974000
SRT                                 21.974000
Panos                               21.974000
Buick                               21.974000
BMW Alpina                          21.974000
Pontiac                             21.974000
Oldsmobile                          21.974000
Dabryan Coach Builders Inc          21.974000
Mobility Ventures LLC               21.974000
CX Automotive                       21.974000
Spyker                              21.974000
PAS Inc - GMC                       21.974000
CCC Engineering                     21.974000
Volvo                               21.974000
Honda                               21.974000
Ram                                 21.974000
VPG                                 21.974000
JBA Motorcars, Inc.                 21.974000
Kia                                 21.974000
Aurora Cars Ltd                     21.974000
ASC Incorporated                    20.600625
American Motors Corporation         20.600625
Environmental Rsch and Devp Corp    20.600625
Eagle                               20.600625
London Coach Co Inc                 20.600625
Autokraft Limited                   20.600625
Suzuki                              20.600625
Morgan                              19.388824
Merkur                              19.388824
Saturn                              19.388824
Lambda Control Systems              19.388824
Shelby                              19.388824
Bill Dovell Motor Car Company       19.388824
Sterling                            19.388824
Hyundai                             19.388824
Grumman Allied Industries           19.388824
Mahindra                            19.109250
Subaru                              18.311667
TVR Engineering Ltd                 18.311667
General Motors                      18.311667
Peugeot                             18.311667
Goldacre                            18.311667
Genesis                             18.311667
McLaren Automotive                  18.311667
London Taxi                         17.372045
Renault                             17.347895
Pininfarina                         17.347895
Volga Associated Automobile         17.347895
Import Foreign Auto Sales Inc       17.347895
Evans Automobiles                   17.347895
Mcevoy Motors                       17.347895
Daewoo                              16.480500
Daihatsu                            16.480500
Panther Car Company Limited         16.480500
Isis Imports Ltd                    16.480500
Geo                                 15.695714
Qvale                               15.695714
Consulier Industries Inc            15.695714
Quantum Technologies                15.695714
MINI                                14.982273
Scion                               14.982273
Bertone                             14.982273
Panoz Auto-Development              14.982273
Grumman Olson                       14.699423
Red Shift Ltd.                      14.330870
Dacia                               14.330870
Yugo                                14.330870
Fiat                                13.733750
smart                                9.694412
Fisker                               6.359255
Name: Fuel Barrels/Year, dtype: float64

<b> (Optional)

In [448]:
vehicles_df.groupby('Make') ['Fuel Barrels/Year'].min().sort_values(ascending=True)

Make
Honda                                0.060000
Toyota                               0.080870
Ford                                 0.103333
Dodge                                0.109412
VPG                                  0.143077
Mobility Ventures LLC                0.143077
GMC                                  0.155000
Chevrolet                            0.155000
BMW                                  1.563190
Cadillac                             3.504650
Hyundai                              3.835583
Audi                                 5.115503
Fisker                               6.359255
Geo                                  7.012979
Volkswagen                           7.324667
Kia                                  7.847857
Lexus                                7.847857
Pontiac                              7.847857
Suzuki                               7.847857
Porsche                              7.984573
Lincoln                              8.240250
Mitsubishi                           8.240250
Mercedes-Benz                        8.246835
Mercury                              8.451538
Volvo                                8.652550
Acura                                8.673947
Scion                                8.908378
Mazda                                8.908378
smart                                9.155833
Nissan                               9.417429
Isuzu                                9.417429
Subaru                               9.694412
Fiat                                 9.694412
Daihatsu                             9.694412
Renault                              9.988182
Plymouth                             9.988182
MINI                                 9.988182
Jaguar                              10.616250
Eagle                               10.632581
Infiniti                            10.632581
McLaren Automotive                  10.794366
Buick                               10.987000
Saturn                              11.365862
Chrysler                            11.771786
Alfa Romeo                          11.771786
Daewoo                              12.207778
Oldsmobile                          12.207778
Jeep                                12.207778
Grumman Olson                       12.328548
Yugo                                12.677308
Saab                                13.184400
Lotus                               13.733750
Land Rover                          13.733750
Ram                                 13.733750
Dacia                               14.330870
Red Shift Ltd.                      14.330870
Peugeot                             14.699423
Bertone                             14.982273
Pininfarina                         14.982273
Panoz Auto-Development              14.982273
Genesis                             14.982273
Panther Car Company Limited         15.695714
American Motors Corporation         15.695714
Consulier Industries Inc            15.695714
Qvale                               15.695714
Quantum Technologies                15.695714
Mcevoy Motors                       16.480500
Merkur                              16.480500
Isis Imports Ltd                    16.480500
Import Foreign Auto Sales Inc       17.347895
Maserati                            17.347895
Wallace Environmental               17.347895
Volga Associated Automobile         17.347895
Evans Automobiles                   17.347895
Bentley                             17.347895
Sterling                            17.347895
Ferrari                             17.347895
CX Automotive                       17.347895
London Taxi                         17.372045
TVR Engineering Ltd                 18.311667
Goldacre                            18.311667
General Motors                      18.311667
Roush Performance                   18.311667
Mahindra                            19.109250
Shelby                              19.388824
Spyker                              19.388824
Grumman Allied Industries           19.388824
Aston Martin                        19.388824
Federal Coach                       19.388824
Autokraft Limited                   19.388824
Dabryan Coach Builders Inc          19.388824
J.K. Motors                         19.388824
Lamborghini                         19.388824
Dutton                              19.388824
Import Trade Services               19.388824
Lambda Control Systems              19.388824
Morgan                              19.388824
Bill Dovell Motor Car Company       19.388824
AM General                          19.388824
ASC Incorporated                    20.600625
Environmental Rsch and Devp Corp    20.600625
London Coach Co Inc                 20.600625
Saleen                              20.600625
BMW Alpina                          20.600625
Bitter Gmbh and Co. Kg              20.600625
Hummer                              20.600625
CCC Engineering                     21.974000
Rolls-Royce                         21.974000
Panos                               21.974000
PAS Inc - GMC                       21.974000
SRT                                 21.974000
JBA Motorcars, Inc.                 21.974000
Aurora Cars Ltd                     21.974000
Saleen Performance                  23.543571
PAS, Inc                            23.543571
Excalibur Autos                     23.543571
Vixen Motor Company                 23.886563
Tecstar, LP                         25.354615
Ruf Automobile Gmbh                 25.354615
Pagani                              25.354615
Maybach                             25.354615
Texas Coach Company                 27.467500
Laforza Automobile Inc              29.964545
Bugatti                             32.961000
Vector                              36.623333
Name: Fuel Barrels/Year, dtype: float64

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [28]:
## your Code here

sort_values()

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [20]:
## Your Code is here